#!/bin/bash
case "${1}" in

	"lproxy") 
		curl www.gatherproxy.com 2>| /dev/null | grep -io '{"proxy_[^}]*}'  | jq -r '. | {_:.PROXY_COUNTRY, IP:.PROXY_IP,PORT:.PROXY_PORT}' -c  | sed 's/["{}]//g' | awk -F, '{ p=substr($3,6); $3="PORT:" sprintf("%d",strtonum("0x" p)); }1' OFS=',' | sed 's/ /_/; s/,IP:/\t/; s/,PORT//;'
	;;
		
	# "gedit")
	#	nohup gedit "$@" 1> /tmp/files/nohup.out 2>&1 & 
	#;;
esac
	
