#!/bin/bash
echo "$@"
case "${1}" in

	"lproxy") 
		curl www.gatherproxy.com 2>| /dev/null | grep -io '{"proxy_[^}]*}'  | jq -r '. | {_:.PROXY_COUNTRY, IP:.PROXY_IP,PORT:.PROXY_PORT}' -c  | sed 's/["{}]//g' | awk -F, '{ p=substr($3,6); $3="PORT:" sprintf("%d",strtonum("0x" p)); }1' OFS=',' | sed 's/,IP:/\t/; s/,PORT//; s/ /_/g; s/^..//' | sed $'s/ *[^\t]*/\x1b[7;1m&\x1b[0m/' | column -t | column -t -s ':'
	;;
		
	"cproxy")
		curl www.gatherproxy.com/proxylist/country/?c=${2} 2>| /dev/null | grep -io '{"proxy_[^}]*}'  | jq -r '. | {_:.PROXY_COUNTRY, IP:.PROXY_IP,PORT:.PROXY_PORT}' -c  | sed 's/["{}]//g' | awk -F, '{ p=substr($3,6); $3="PORT:" sprintf("%d",strtonum("0x" p)); }1' OFS=',' | sed 's/,IP:/\t/; s/,PORT//; s/ /_/g; s/^..//' | sed $'s/ *[^\t]*/\x1b[7;1m&\x1b[0m/' | column -t | column -t -s ':'
	;;
	
	"gedit")
		nohup gedit "${2}" 1>| /tmp/files/nohup.out 2>&1 & 
	;;
	
	"hex")
		cat /dev/stdin  | hexdump -v -e '"\x" 1/1 "%02X"' && echo ;
	;;
	
	"lh")
		if [ -z "${2}" ] ;
			then
				ls -FlAshZid --color=auto .*
			else
				ls -FlAshZid --color=auto ${2}/.*
		fi
	;;
	
	"network")
		ip addr | grep 255 ; echo ;
		curl -s http://whatismyip.akamai.com/ ; echo; 
		#MAC
		#apr scan, tcp scan 
		ping -c 2 google.com ; 
	;;
	
	"system")
		tty ; echo ;
		iostat ; echo
		echo ${0} ; echo ;
		w ; echo ;
		who -a ; echo ;
		uptime ; echo ;
		stty -a ;
		uname -a ; echo ;
		ls -lshZid /; echo ;
		la /dev/sd[a..b] ;
		la /dev/sd[a-b][0-9] ; echo ;
		fdisk -l ; echo ;
		#du -h / ;
		df -ahT ; echo ;
		printenv ; echo ;
		cat /proc/cpuinfo ; echo;
		lscpu ; echo ;
	;;
	
	"gitup")
		git remote show origin ;
		git status -s ;
		echo -e "\x0a\x1b[7m\x57\x61\x6E\x74\x20\x61\x6C\x6C\x20\x63\x6F\x6D\x6D\x69\x74\x73\x20\x75\x6E\x73\x74\x61\x67\x65\x64\x20\x3F\x3F\x1b[27m\x0A"
		read r1 ;
		if echo "${r1}" | 
			grep -iq "^y" ;	then
				
			git reset ;
		fi
		echo -e "\x0a\x1b[7m\x67\x69\x74\x20\x61\x64\x64\x20\x3F\x3F\x1b[27m\x0A"
		read r1 ;
		if echo "${r1}" | 
			grep -iq "^y" ;	then
			git add . ;
		fi
		git status -s ;
		echo -e "\x0a\x1b[7m\x43\x6F\x6E\x74\x69\x6E\x75\x65\x20\x3F\x3F\x1b[27m\x0A"
		read -p "" ;
		git commit -m "0";
		#echo -e "\x0a\x1b[2m\x67\x69\x74\x20\x6C\x6F\x67\x0A"
		#git log;
		git push ;
	;;
	
esac
	
